name: Publish package to GitHub Packages
on: push
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Package with Maven
        run: mvn package
      - name: Deploy to AWS Elastic Beanstalk
        uses: Amraneze/aws-beanstalk-deploy@master
        with:
          region: AWS_REGION
          environment_name: elastic-beanstalk-application
          application_name: maven-app
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3_bucket_name: elasticbeanstalk-maven
          s3_file_path: maven-app.war
          ebs_version_label: 1.0.0
